# Generated by Django 5.2.1 on 2025-12-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ysera', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerimage',
            name='Type',
            field=models.CharField(choices=[('price', 'price'), ('promo code', 'promo code')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='offerimage',
            name='descripton',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='offerimage',
            name='offers',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='offerimage',
            name='where_to_display',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='none', max_length=10),
        ),
    ]
