# Generated by Django 5.2.1 on 2025-12-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ysera', '0002_offerimage_type_offerimage_descripton_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerimage',
            name='offer_applies_to',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
