# Generated by Django 5.2.1 on 2025-12-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ysera', '0003_offerimage_offer_applies_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('discount_percent', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
