# Generated by Django 5.2.1 on 2025-12-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ysera', '0004_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(default='', max_length=100)),
                ('hot', models.CharField(choices=[('none', 'none'), ('hot', 'hot'), ('trending', 'trending'), ('bestselling', 'bestsellin')], default='none', max_length=150)),
                ('slug', models.SlugField(blank=True, default='', null=True, unique=True)),
            ],
        ),
    ]
