# Generated by Django 5.2.1 on 2025-12-23 12:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ysera', '0005_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='hot',
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_method', models.CharField(choices=[('online', 'Online Payment'), ('cod', 'Cash on Delivery')], default='cod', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(default='', max_length=1000)),
                ('small_title', models.CharField(default='', max_length=1000)),
                ('small_desc', models.CharField(default='', max_length=1000)),
                ('brand_name', models.CharField(default='', max_length=1000)),
                ('desc', models.TextField(default='')),
                ('size', models.TextField(default='')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('del_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('save_upto', models.IntegerField(default=1)),
                ('delivery_times', models.IntegerField(default=1)),
                ('new', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=150)),
                ('stock_status', models.CharField(choices=[('in stock', 'In Stock'), ('out of stock', 'Out of Stock')], default='in stock', max_length=150)),
                ('where_in_home', models.CharField(choices=[('bestseller', 'bestseller'), ('newarrivals', 'coesmetic'), ('toprated', 'toprated')], default='none', max_length=100)),
                ('where_to_display', models.CharField(choices=[('none', 'None'), ('home', 'Home')], default='none', max_length=10)),
                ('slug', models.SlugField(blank=True, default='', null=True, unique=True)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ysera.category')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ysera.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ysera.product')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ysera.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ysera.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('img_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='images')),
                ('slug', models.SlugField(blank=True, default='', null=True, unique=True)),
                ('p_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ysera.product')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='angels', max_length=100)),
                ('last_name', models.CharField(default='angels', max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('mobile', models.CharField(max_length=15)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
