# Generated by Django 5.2.1 on 2025-12-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ysera', '0006_remove_category_hot_cart_order_passwordresetotp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
