# Generated by Django 5.2.1 on 2025-12-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ysera', '0009_alter_product_where_in_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='where_in_home',
            field=models.CharField(choices=[('bestseller', 'best seller'), ('newarrivals', 'new arrivals'), ('toprated', 'top rated'), ('bridalsets', 'Bridal Sets')], default='none', max_length=100),
        ),
    ]
