# Generated by Django 6.0 on 2025-12-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ysera', '0010_alter_product_where_in_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='priority',
            field=models.CharField(choices=[('first', 'first'), ('No', 'No')], default='none', max_length=10),
        ),
    ]
