# Generated by Django 6.0 on 2025-12-30 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ysera', '0011_productimage_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='small_desc',
            new_name='point1',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='small_title',
            new_name='point2',
        ),
    ]
