# Generated by Django 6.0 on 2025-12-31 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ysera', '0012_rename_small_desc_product_point1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerimage',
            name='where_to_display',
            field=models.CharField(choices=[('1', 'home-1'), ('2', 'home-2'), ('3', 'home-3'), ('4', 'home-4'), ('5', 'home-5'), ('6', 'search')], default='none', max_length=10),
        ),
    ]
